### ISSUE TITLE
Emulate factors in SQL

### ISSUE THREAD

**Issue by ashiklom** [ashiklom/dbhelpers#3]
Factors are very useful in R, and lend themselves nicely to SQL storage. It would be nice to have some shortcut functions for this sort of operation:

```r
library(dplyr)
db <- src_sqlite('mydatabase.sqlite')
raw_table <- tbl(db, 'values_table') # Stores integer representations of column X
X_levels <- tbl(db, 'zlevels___X') %>% # Stores integer codes (X) and levels (levels)
  arrange(X) %>%
  collect %>%
  .[['levels']]
factor_table <- mutate(raw_table, X = 'levels<-'(as.factor(X), X_levels)')
```

# Roadmap
* [ ] Read factor tables (SQL -> R)
  - [ ] Pass arguments explicitly
  - [ ] Shortcuts based on a standardized name pattern (e.g. `column___factor`)
* [ ] Write factor tables (R -> SQL)
  - [ ] Test with SQLite
  - [ ] Test with PostgreSQL
